export const KEYWORDS_BASE_URL = 'https://raw.githubusercontent.com/potatoqualitee/calm-the-chaos/main/keywords/categories';
export const CONTEXT_GROUPS_URL = 'https://raw.githubusercontent.com/potatoqualitee/calm-the-chaos/main/keywords/context-groups.json';
export const DISPLAY_CONFIG_URL = 'https://raw.githubusercontent.com/potatoqualitee/calm-the-chaos/main/keywords/display-config.json';
// Auto-generated by scripts/trending/update.js on a schedule; raw URL so new
// phrases go live without waiting for a Pages redeploy
export const TRENDING_URL = 'https://raw.githubusercontent.com/potatoqualitee/mutesky/main/keywords/trending.json';
